-- AlterTable
ALTER TABLE `courses` MODIFY COLUMN `venueType` ENUM('HOTEL', 'ON_PREMISE', 'CLIENT_FACILITY', 'ONLINE') NULL;

-- AlterTable
ALTER TABLE `course_runs` MODIFY COLUMN `venueType` ENUM('HOTEL', 'ON_PREMISE', 'CLIENT_FACILITY', 'ONLINE') NULL;

-- AlterTable
ALTER TABLE `venues` MODIFY COLUMN `venueType` ENUM('HOTEL', 'ON_PREMISE', 'CLIENT_FACILITY', 'ONLINE') NULL;

