-- AlterTable
ALTER TABLE `course_runs` MODIFY `status` ENUM('DRAFT', 'PENDING', 'CONFIRMED_PENDING_TA_APPROVAL', 'ACTIVE', 'INACTIVE', 'CONFIRMED', 'CONFIRMED_PENDING_CONFIRMATION_EMAILS', 'IN_PROGRESS', 'PENDING_BILLING', 'COMPLETED', 'CANCELLED', 'ARCHIVED', 'PUBLISHED', 'ONGOING') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `courses` ADD COLUMN `learningObjectives` TEXT NULL,
    ADD COLUMN `status` ENUM('DRAFT', 'PENDING', 'CONFIRMED_PENDING_TA_APPROVAL', 'ACTIVE', 'INACTIVE', 'CONFIRMED', 'CONFIRMED_PENDING_CONFIRMATION_EMAILS', 'IN_PROGRESS', 'PENDING_BILLING', 'COMPLETED', 'CANCELLED', 'ARCHIVED', 'PUBLISHED', 'ONGOING') NOT NULL DEFAULT 'ACTIVE',
    MODIFY `courseOutline` TEXT NULL;
